export const ADD_POSTS = "ADD_POSTS";
export const POSTS_FAILED = "POSTS_FAILED";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";


export const ALERT_MSG = "ALERT_MSG";
export const ALERT_DISMISS = "ALERT_DISMISS";
// export const ALERT_INFO = "ALERT_INFO";
// export const ALERT_FAIL = "ALERT_FAIL";
export const ACCOUNT_UPDATE_SUCCESS = "ACCOUNT_UPDATE_SUCCESS";
export const ACCOUNT_UPDATE_FAILED = "ACCOUNT_UPDATE_FAILED";